### ISSUE TITLE
No sentence ID seems to cause a problem ?

### ISSUE THREAD

**Issue by g8dhe** [philcrump/habrotate#12]
Telemetry:
$$HABUni,10:37:24,51.747108,-1.803100,05848_C705
$$HABUni,10:37:43,51.743641,-1.805210,05897_6352
$$HABUni,10:38:03,51.740051,-1.807440,05944_71F0
$$HABUni,10:38:22,51.736481,-1.809510,05994_CC47
Error:
C:\Program Files (x86)\HABRotate>habrotate-cli
##### HABrotate

Parsing config.json..
Receiver Station Location: Lat: 50.82803 Lon: -0.38246 Altitude: 12.0
UDP Configuration: IP: 127.0.0.1 Port: 12000
Control Configuration: Hysteresis = 5 degrees, Overshoot = 3 degrees.
Querying flights..
1: APJ09
2: Stargazing
3: Eagle Eclipse launch
4: Kent_HAB1 - TODAY
Select Flight number: 4
Querying position..
Traceback (most recent call last):
  File "habrotate-cli.py", line 200, in <module>

  File "habrotate-cli.py", line 99, in grab_position
    flight_telemetry[i]["longitude"] = last_string["doc"]["data"]["longitude"];
KeyError: 'sentence_id'

C:\Program Files (x86)\HABRotate>

**Comment by philcrump** [comment]
Yep, known, see #10

There's no good way to order telemetry out of the database instead of by sentence_id.
- Payload Time isn't present when there isn't a fix, and wraps daily.
- Received Time is very unreliable (found that the ASTRA PC was 45 minutes out last night), only needs one person with it configured to be in the future to break everything.
- Uploaded Time is completely variable when there is a chasecar involved, which will upload old packets later, (and _will_ break it).

If you have any ideas, do let me know!
